name: Release

on:
  workflow_call:
    secrets:
      github-token:
        required: false
    inputs:
      main-branch-name:
        required: false
        type: string
      release-commands:
        required: false
        type: string
      node-version:
        required: false
        type: string
      npm-version:
        required: false
        type: string
      yarn-version:
        required: false
        type: string
      pnpm-version:
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          main-branch-name: ${{ inputs.main-branch-name }}
          node-version: ${{ inputs.node-version }}
          npm-version: ${{ inputs.npm-version }}
          yarn-version: ${{ inputs.yarn-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: Version
        uses: ./.github/actions/release
        with:
          release-commands: ${{ inputs.release-commands }}
          github-token: ${{ secrets.github-token }}
